### ISSUE TITLE
Pagmo Algorithmn

### ISSUE THREAD

**Issue by rshuka** [rshuka/PASS#23]
- CMA-ES
- Differential Evolution (DE)
- Simple Genetic Algorithm
- Artificial Bee Colony (ABC)
- Corana’s Simulated Annealing (SA)
- Compass Search (CS)

All from Pagmo2: https://esa.github.io/pagmo2/docs/algorithm_list.html

- Add a tutorial how to use it :)

**Comment by pschiffmann** [comment]
Both SA and CS are now implemented. I still need to set recommended default values for the optimiser parameters – and for that, I have to find papers that recommend default values. Whenever I find something while working on the documentation task, I'll update the code too.
